//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Печать фото.
    /// </summary>
    // *** Start programmer edit section *** (ПечатьФото CustomAttributes)

    // *** End programmer edit section *** (ПечатьФото CustomAttributes)
    [AutoAltered()]
    [Caption("Печать фото")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПечатьФотоE", new string[] {
            "Размер as \'Размер\'",
            "СделатьФото.КолВоФото as \'Количество фото\'",
            "СделатьФото.КатегорФото as \'Категория фото\'"})]
    [View("ПечатьФотоL", new string[] {
            "Размер as \'Размер фото\'",
            "СделатьФото.КатегорФото as \'Категория фото\'",
            "СделатьФото.КолВоФото as \'Количество фото\'"})]
    public class ПечатьФото : ICSSoft.STORMNET.DataObject
    {
        
        private string fРазмер;
        
        private IIS.Fotokiosk6.СделатьФото fСделатьФото;
        
        // *** Start programmer edit section *** (ПечатьФото CustomMembers)

        // *** End programmer edit section *** (ПечатьФото CustomMembers)

        
        /// <summary>
        /// Размер.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФото.Размер CustomAttributes)

        // *** End programmer edit section *** (ПечатьФото.Размер CustomAttributes)
        [StrLen(255)]
        public virtual string Размер
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФото.Размер Get start)

                // *** End programmer edit section *** (ПечатьФото.Размер Get start)
                string result = this.fРазмер;
                // *** Start programmer edit section *** (ПечатьФото.Размер Get end)

                // *** End programmer edit section *** (ПечатьФото.Размер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФото.Размер Set start)

                // *** End programmer edit section *** (ПечатьФото.Размер Set start)
                this.fРазмер = value;
                // *** Start programmer edit section *** (ПечатьФото.Размер Set end)

                // *** End programmer edit section *** (ПечатьФото.Размер Set end)
            }
        }
        
        /// <summary>
        /// Печать фото.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФото.СделатьФото CustomAttributes)

        // *** End programmer edit section *** (ПечатьФото.СделатьФото CustomAttributes)
        [PropertyStorage(new string[] {
                "СделатьФото"})]
        [NotNull()]
        public virtual IIS.Fotokiosk6.СделатьФото СделатьФото
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФото.СделатьФото Get start)

                // *** End programmer edit section *** (ПечатьФото.СделатьФото Get start)
                IIS.Fotokiosk6.СделатьФото result = this.fСделатьФото;
                // *** Start programmer edit section *** (ПечатьФото.СделатьФото Get end)

                // *** End programmer edit section *** (ПечатьФото.СделатьФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФото.СделатьФото Set start)

                // *** End programmer edit section *** (ПечатьФото.СделатьФото Set start)
                this.fСделатьФото = value;
                // *** Start programmer edit section *** (ПечатьФото.СделатьФото Set end)

                // *** End programmer edit section *** (ПечатьФото.СделатьФото Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПечатьФотоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПечатьФотоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПечатьФотоE", typeof(IIS.Fotokiosk6.ПечатьФото));
                }
            }
            
            /// <summary>
            /// "ПечатьФотоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПечатьФотоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПечатьФотоL", typeof(IIS.Fotokiosk6.ПечатьФото));
                }
            }
        }
    }
}
